### ISSUE TITLE
Is it possible to use this tool for big projects like Prestashop etc?

### ISSUE THREAD

**Issue by kstalega** [designsecurity/progpilot#12]
Hi,

I've tried your tool for scaning Prestashop, using this command:
```
php progpilot_v0.4.0.phar - ~/Documents/static-analysis/prestashop-1.7.2.4/
```
But the test lasted for over 24 hours and it did not end. What can I do to get rid of this problem?

Best regards,
KS

**Comment by eric-therond** [comment]
Hi
Maybe you could try the dev version :
https://github.com/designsecurity/progpilot/tree/master/builds

and when you do static analysis you have to know your targets very precisely :
- Progpilot itself should know a big CMS like prestashop (for example the functions that do validation of insecure data and [the sinks](http://doc.prestashop.com/display/PS16/Best+Practices+of+the+Db+Class)) otherwise there will be a lot of false positives, I will look at this.
- In addition, you have to [configure progpilot](https://github.com/designsecurity/progpilot/blob/master/projects/example_config/configuration.yml) to exclude files that are not relevant to the analysis (like dependencies, ressources, images ect), in my case I have this *exclude_files.json* :
```javascript
{
    "exclude_files":
    [
    ],
    "exclude_folders":
    [
        "/home/eric/dev/prestashop/vendor/",
        "/home/eric/dev/prestashop/localization/"
    ]
}
```
With the dev version and the previous configuration progpilot runs much faster :
```bash
real    10m58,886s
user    8m43,893s
sys     0m1,498s
```
Look also at the [options](https://github.com/designsecurity/progpilot/blob/master/docs/API.md) of progpilot that provide configurable parameters to optimize time and memory of analysis.

Eric
