### ISSUE TITLE
I can't install Progpilot on PHP < 7.4

### ISSUE THREAD

**Issue by andreasciamanna** [designsecurity/progpilot#22]
The documentation says:

> The minimum version of PHP needed to run Progpilot is 7.0.25

However, due to the library requiring `ircmaxell/php-cfg` (which is requiring PHP 7.4) it's impossible to install the library with versions of PHP older than 7.4.

As I'm dealing with legacy code which for which we must provide support for older 7.* versions of PHP, I'm unable to use this library to scan for security issue.

**Comment by eric-therond** [comment]
Hi
I have updated `composer.json` and the FAQ
the minimum php version to run progpilot 0.8.0 is 7.2.5 but not because of `ircmaxell/php-cfg` but other dependencies
did you try progpilot 0.8.0?

so you need php 7.2.5 or higher to run progpilot but progpilot can then scan whatever php code for security issues

Eric

**Comment by eric-therond** [comment]
Done in v1.0.0
